ViewModels/ReportsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVC5CentrexDataProcessor.Models;

namespace MVC5CentrexDataProcessor.ViewModels
{
    public class ReportsViewModel
    {
        public IEnumerable<Record09> Record09S { get; set; }
        public IEnumerable<Record10> Record10S { get; set; }  

    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using MVC5CentrexDataProcessor.Models;
using MVC5CentrexDataProcessor.ViewModels;

namespace MVC5CentrexDataProcessor.Controllers
{
    public class ReportsController : Controller
    {

        private CentrexEntities db = new CentrexEntities();


        // GET: /Reports
        public ActionResult Index()
        {

            return View();
        }


        [HttpPost]
        // POST: /Reports
        public ActionResult Index(string searchString, string recordType)
        {


            if (recordType == "09")
            {
               

                return View(Record09Report(searchString));
            }

            if (recordType == "10")
            {
                var records = db.Record10.ToList();

                if (!string.IsNullOrEmpty(searchString))
                {
                    records = db.Record10.Where(r => r.Telephone_Number.Contains(searchString)).ToList();
                }

                return View("Record10Report", records);
               
            }


            return View();
        }

        public ActionResult Record09Report(string searchString)
        {
            var records = db.Record09.ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                records = db.Record09.Where(r => r.Telephone_Number.Contains(searchString)).ToList();
            }

            return View(records);
        }

        // GET: /Reports/Record10Report
        public ActionResult Record10Report() 
        {
            return View();
        }



        // GET: /Reports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record10 record10 = db.Record10.Find(id);
            if (record10 == null)
            {
                return HttpNotFound();
            }
            return View(record10);
        }



	}
}

Views/Reports/Details.cshtml
@model MVC5CentrexDataProcessor.ViewModels.ReportsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reports</h4>
	<hr />
    <dl class="dl-horizontal">

        <dd>
            @Html.DisplayFor(model => model.Record10S)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Reports/Index.cshtml
@{
    Html.RenderPartial("_Search");
}

Views/Reports/Record09Report.cshtml
@model IEnumerable<MVC5CentrexDataProcessor.Models.Record09>

@{
    ViewBag.Title = "ATT Record 09 Report";  
}

@{

    Html.RenderPartial("_Search");

}

<h2>Centrex Record 09 Report</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Record_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Billing_Telephone_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Call_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Call_Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Invoice_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone_Number)
        </th>
        <th></th>
    </tr>


@if (Model != null)
{

    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Record_Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Billing_Telephone_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number_of_Calls)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number_of_Seconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invoice_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone_Number)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.Id})
            </td>
        </tr>
    }
}

</table>

Views/Reports/Record10Report.cshtml
@model IEnumerable<MVC5CentrexDataProcessor.Models.Record10>

@{
    ViewBag.Title = "ATT Record 10 Report";  
}

@{

    Html.RenderPartial("_Search");

}

<h2>Centrex Record 10 Report</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Record_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Billing_Telephone_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number_of_Calls)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number_of_Seconds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Invoice_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone_Number)
        </th>
        <th></th>
    </tr>


@if (Model != null)
{

    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Record_Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Billing_Telephone_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number_of_Calls)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number_of_Seconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invoice_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone_Number)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.Id})
            </td>
        </tr>
    }
}

</table>

Views/Reports/_Search.cshtml
<h2>Centrex Data Report</h2>

@using (Html.BeginForm("Index", "Reports", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4>Search</h4>
    <br/>
    <br/>

    <div class="form-group">
        @Html.Label("Record Type:")
        <select id="recordType" name="recordType" class="form-control">
            <option value="07">07</option>
            <option value="09">09</option>
            <option value="10">10</option>
            <option value="12">12</option>
        </select>
    </div>


    <div class="form-group">
        @Html.Label("Phone Number:")
        <input type="text" class="form-control" name="searchString" value=""/>
    </div>  
    
   

  
    <div class="form-group">
        <input type="submit" name="Search" value="Search" class="btn btn-default"/>
    </div>
    <div class="row">
        <div class="col-md-2"><br/>
        </div>
    </div>
}